version: "3"


services:
  workspace:
    build:
      context: ./workspace
    volumes:
      - ${CODE_PATH}:${CONTAINER_CODE_PATH}
  nginx:
#    environment:
#      - CONTAINTER_MAPPING_PATH=123
#    env_file:
#      - ./.docker.env
    build:
      context: ./nginx
      args:
        - RUN_CONTAINTER_MAPPING_PATH=${CONTAINER_CODE_PATH}
    volumes:
      - ${CODE_PATH}:${CONTAINER_CODE_PATH}
    command: ${CONTAINER_CODE_PATH}/docker/nginx/nginx.conf
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm:php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - RUN_CONTAINTER_MAPPING_PATH=${CONTAINER_CODE_PATH}
        - RUN_CONTAINTER_PHP_CONF_PATH=/usr/local/etc/php
        - LOCAL_PHP_CONF_PATH=./conf/php.ini
    volumes:
      - ${CODE_PATH}:${CONTAINER_CODE_PATH}
    expose:
      - "9000"
    ports:
      - "9000:9000"
